version: '3.3'

services:
  pubsuby:
    image: ghcr.io/stliakis/pubsuby-pubsuby:production
    command: bash -c "/app/startup.sh;npm run start"
    deploy:
      replicas: 5
      update_config:
        failure_action: rollback
        delay: 30s

  proxy:
    image: ghcr.io/stliakis/pubsuby-proxy:production
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        delay: 30s
